name: Test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.6
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install --upgrade coverage
                  python -m pip install --upgrade nose
                  python -m pip install --upgrade rednose
                  python -m pip install -e ".[d]"

            - name: Unit tests
              run: |
                  nosetests
